title: Candace Broussard
email: broussardcandace@ymail.com
description: >-
  This is the personal blog of Candace Broussard
baseurl: "/"
url: "https://cmbrouss.github.io/personal-blog"
github_username:  cmbrouss

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed